# Generated by Django 5.1.5 on 2025-03-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Theme Name', max_length=100, unique=True)),
                ('primary_color', models.CharField(help_text='Primary Color (Hex Code)', max_length=7)),
                ('secondary_color', models.CharField(help_text='Secondary Color (Hex Code)', max_length=7)),
                ('background_color', models.CharField(help_text='Background Color (Hex Code)', max_length=7)),
                ('text_color', models.CharField(help_text='Text Color (Hex Code)', max_length=7)),
                ('button_color', models.CharField(help_text='Button Background Color', max_length=7)),
                ('button_text_color', models.CharField(help_text='Button Text Color', max_length=7)),
                ('font_family', models.CharField(default='Arial', help_text='Font Family', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Set Active Theme')),
            ],
        ),
    ]
