# Generated by Django 5.1.5 on 2025-03-27 18:11

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='background_color',
            field=colorfield.fields.ColorField(default='#F0F0F0', help_text='Background Color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='theme',
            name='button_color',
            field=colorfield.fields.ColorField(default='#007BFF', help_text='Button Background Color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='theme',
            name='button_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Button Text Color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='theme',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#000000', help_text='Primary Color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='theme',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Secondary Color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='theme',
            name='text_color',
            field=colorfield.fields.ColorField(default='#000000', help_text='Text Color', image_field=None, max_length=25, samples=None),
        ),
    ]
