# Generated by Django 5.2.4 on 2025-07-17 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('pincode', models.CharField(max_length=10)),
                ('locality', models.CharField(max_length=100)),
                ('address_line', models.TextField(help_text='Address (Area and Street)')),
                ('city', models.CharField(max_length=50, verbose_name='City/District/Town')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work')], default='home', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
